# We specify a version for Compose. Make sure Compose is compatible with Docker
version: "3.9"
services:
  vite_docker: # Define the client service so we can run it in an isolated environment.
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev # The client service requires a docker file to be specified. For development, we’re going to use the Dockerfile.dev file.
    ports:
      - "8000:5173" # We map the port 8000 to Docker. Vite runs on port 5173, so we need to tell Docker which port to expose for our application.
    volumes:
      - "/app/node_modules"
      - "./:/app"